spring:
  datasource:
    url: jdbc:mysql://192.168.27.236:3306/file_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: devops
    password: Acqu_userd@123
  servlet:
    multipart:
      max-file-size: 20480MB
      max-request-size: 20480MB

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
server:
  port: 8888

# 文件共享位置(minio)
minio:
  endpoint: http://192.168.27.232:9000
  file_download_point: http://192.168.27.232:9000
  access_key: oypNSAaCNtV2mj7N
  secret_key: tW6ewUTCun8T381bcIbROQa541bOmj13
  bucket: package

# 文件共享位置(local)
erupt:
  uploadPath: /root/file_management/data