spring:
  datasource:
    url: jdbc:mysql://47.95.36.245:3306/file_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: temp
    password: databpsPass4you!
  servlet:
    multipart:
      max-file-size: 20480MB
      max-request-size: 20480MB

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
server:
  port: 8888

# 文件共享位置
erupt:
  uploadPath: /soft/data

minio:
  endpoint: http://47.95.36.245:9000
  file_download_point: http://47.95.36.245:39862
  access_key: oypNSAaCNtV2mj7N
  secret_key: tW6ewUTCun8T381bcIbROQa541bOmj13
  bucket: package