spring:
  datasource:
    url: jdbc:mysql://47.95.36.245:3306/file_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: temp
    password: databpsPass4you!
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
server:
  port: 8888

# 文件共享位置
erupt:
  uploadPath: /Users/hongyan/Desktop/shuke/shareFiles